# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformshCli < Formula
  desc "Platform.sh CLI"
  homepage "https://docs.platform.sh/administration/cli.html"
  version "5.0.12"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/platformsh/cli/releases/download/5.0.12/platform_5.0.12_darwin_all.tar.gz"
    sha256 "3c8422dc9f67c8a2a7a11f6c707f071ee1b7aec3ff21d7b51157b3ea5e0337c0"

    def install
      bin.install "platform"
      generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformsh/cli/releases/download/5.0.12/platform_5.0.12_linux_arm64.tar.gz"
      sha256 "b049e5e5ed2504154dc8fe5c06a7afe856dc040c4db8b69d5b0d02ac14bc595e"

      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformsh/cli/releases/download/5.0.12/platform_5.0.12_linux_amd64.tar.gz"
      sha256 "45dd7b574a490d0c19259d36cb1f1ab5de0d0b29a66b0a88852ece33e24b2900"

      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/platform --version"
  end
end
