# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformshCli < Formula
  desc "Platform.sh CLI"
  homepage "https://docs.platform.sh/administration/cli.html"
  version "5.2.0"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/platformsh/cli/releases/download/5.2.0/platform_5.2.0_darwin_all.tar.gz"
    sha256 "053728d308adadb9bae140dd3412930e3646dcb699b32d4b511339a339c06abe"

    def install
      bin.install "platform"
      generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/platformsh/cli/releases/download/5.2.0/platform_5.2.0_linux_amd64.tar.gz"
        sha256 "a2e11a2c53738ce373dde65ab1bad6eac5aafc21232a2f33d0dd34e69ef82995"

        def install
          bin.install "platform"
          generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/platformsh/cli/releases/download/5.2.0/platform_5.2.0_linux_arm64.tar.gz"
        sha256 "c10188959b17570b09c9051d7c5985ee2808b1023c43bc07571bc072a6d1f9c5"

        def install
          bin.install "platform"
          generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
        end
      end
    end
  end

  test do
    system "#{bin}/platform --version"
  end
end
