# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformshCli < Formula
  desc "Platform.sh CLI"
  homepage "https://docs.platform.sh/administration/cli.html"
  version "5.0.3"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/platformsh/cli/releases/download/5.0.3/platform_5.0.3_darwin_all.tar.gz"
    sha256 "2b82d0f42d5f681e69549f900bbf1ec6824de5ad377a72b62008425224493685"

    def install
      bin.install "platform"
      generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/platformsh/cli/releases/download/5.0.3/platform_5.0.3_linux_arm64.tar.gz"
      sha256 "ab9e46f7951492f7406efb9050665e58e68a7d2a2fdeca7168adc7c97b0678ef"

      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/platformsh/cli/releases/download/5.0.3/platform_5.0.3_linux_amd64.tar.gz"
      sha256 "f1e10a12ae610b8c84fd83f2cb51d6f09a57a9efed07d391c0ab31e91af49f3c"

      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/platform --version"
  end
end
