# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpsunCli < Formula
  desc "Upsun CLI"
  homepage "https://docs.deployfriday.net/administration/cli.html"
  version "5.0.15"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/platformsh/cli/releases/download/5.0.15/upsun_5.0.15_darwin_all.tar.gz"
    sha256 "94d96d7e2f80d8689d4dd3008beb48a4a9d46e6669d436def8348aaad2315cc9"

    def install
      bin.install "upsun"
      generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/platformsh/cli/releases/download/5.0.15/upsun_5.0.15_linux_amd64.tar.gz"
        sha256 "e0f62c74f4782d5bc8bde6da4eba251276bbce926c56976c040f266005904547"

        def install
          bin.install "upsun"
          generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/platformsh/cli/releases/download/5.0.15/upsun_5.0.15_linux_arm64.tar.gz"
        sha256 "41189b8999baf3c03effb9677972f2c419a3726ff05b96daf9b246790b41e8fa"

        def install
          bin.install "upsun"
          generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
        end
      end
    end
  end

  test do
    system "#{bin}/upsun --version"
  end
end
