# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpsunCli < Formula
  desc "Upsun CLI"
  homepage "https://docs.upsun.com/administration/cli.html"
  version "5.2.0"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    url "https://github.com/platformsh/cli/releases/download/5.2.0/upsun_5.2.0_darwin_all.tar.gz"
    sha256 "e21a93a915f79466c4d3a0a33d5d8392a5193f95f391cab5b6f8a729545c9340"

    def install
      bin.install "upsun"
      generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/platformsh/cli/releases/download/5.2.0/upsun_5.2.0_linux_amd64.tar.gz"
        sha256 "6cbcde63de5ff826dc74c385510b3491b4520184dff799d292ea55c1b4761c1b"

        def install
          bin.install "upsun"
          generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/platformsh/cli/releases/download/5.2.0/upsun_5.2.0_linux_arm64.tar.gz"
        sha256 "7ef5dbd7e24eb04c40e8a04209bed42d850168a6e04ad8848e9c8bc3f3881543"

        def install
          bin.install "upsun"
          generate_completions_from_executable(bin/"upsun", "completion", shells: [:bash, :zsh])
        end
      end
    end
  end

  test do
    system "#{bin}/upsun --version"
  end
end
